import "./globals.css";
// fonts
import { aldrich } from "@/fonts/fonts";
// components
import Navbar from "@/components/Navbar/Navbar";
import Social from "@/components/Social/Social";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aldrich.className}>
        <Navbar />
        <Social />
        {children}
      </body>
    </html>
  );
}
